### ISSUE TITLE
大佬，您好~想询问该插件如何使用?

### ISSUE THREAD

**Issue by AmatsukaMao** [c98cmka/0xPvpPlugin#2]
导入后能够开启设置视窗但似乎没有办法实际有该功能（主要是测试50半血自动选择）效果，并且忍者的LB似乎会被自动替换成黑魔的技能，想询问是不是在哪个安装过程中出错了，感谢您~

**Comment by c98cmka** [comment]
50血选中的功能只对pvp地图中的敌方玩家有效，要测试的话去狼狱单挑或者战场55。星遁天诛变成磁暴是防误按的，目标血低于50%就会变回去了

**Comment by AmatsukaMao** [comment]
感謝大佬
