### ISSUE TITLE
请问如何打开设置面板？

### ISSUE THREAD

**Issue by Dmmndbox** [c98cmka/0xPvpPlugin#2]
没事.... 我从链接安装就可以显示设置面板了... 但是请问这个只适用于武士/忍者吗？  其他的能用吗

**Comment by c98cmka** [comment]
雷达移速位移是通用的，对应职业tab页里的功能只能对应职业用

**Comment by c98cmka** [comment]
本来还做了dk白魔的一点功能，感觉不太实用就删了
