### ISSUE TITLE
无视镰刀LB功能疑似会导致游戏崩溃

### ISSUE THREAD

**Issue by Dust0818** [c98cmka/0xPvpPlugin#3]
如题，在勾选该功能后，视野范围内敌方钐镰客使用LB会直接导致游戏进程崩溃。
取消勾选该功能后恢复正常。

**Comment by c98cmka** [comment]
没能复现BUG，姑且是改了一下，还有问题的话再说

**Comment by fsdsafsdfdsfsd** [comment]
> 没能复现BUG，姑且是改了一下，还有问题的话再说

还是勾选无视镰刀LB选项就会马上游戏崩溃

**Comment by c98cmka** [comment]
会崩溃的话先不要用了，下个版本移除这个功能

**Comment by Dust0818** [comment]
耽误佬的时间了，抱歉
